// ============================================================================
// Website Build Package generator
// ----------------------------------------------------------------------------
// Assembles the full "Website Build Package" (sections A–M) as Markdown and as
// a structured JSON object for developer / Claude / Codex handoff.
// ============================================================================

import type { ProjectBundle, SystemSettings } from "@/types";
import { formatCurrency } from "@/lib/format";
import { listToSentence } from "./text";
import { buildHandoffPrompt } from "./handoffPrompt";

export function buildPackageMarkdown(
  bundle: ProjectBundle,
  settings: SystemSettings,
): string {
  const { submission: s, project, content, pages, seo, assets } = bundle;
  const L: string[] = [];
  const p = (line = "") => L.push(line);
  const phone = s.contactPhone || settings.defaultPhone;
  const email = s.contactEmail || settings.defaultContactEmail;

  p(`# Website Build Package — ${s.businessName}`);
  p();
  p(`> Generated by the ${settings.companyName} WebBuilder Workspace`);
  p(`> Status: **${project.status.replace(/_/g, " ")}**  ·  Package: ${project.packageSelected}`);
  p();

  // A. Client Info
  p(`## A. Client Info`);
  p(`- Client name: ${s.clientName}`);
  p(`- Business name: ${s.businessName}`);
  p(`- Email: ${s.email}`);
  p(`- Phone: ${s.phone}`);
  p(`- Location / area served: ${s.location || "—"}`);
  p(`- Industry: ${s.industry}`);
  p(`- Timeline: ${s.timeline || "—"}`);
  p();

  // B. Business Summary
  p(`## B. Business Summary`);
  p(content?.businessSummary || s.businessDescription || "—");
  p();
  if (content) {
    p(`**Target audience:** ${content.targetAudience}`);
    p();
    p(`**Website objective:** ${content.websiteObjective}`);
    p();
  }

  // C. Brand Direction
  p(`## C. Brand Direction`);
  if (content) {
    p(content.brandDirection);
    p();
    p(`**Tone:** ${content.brandTone}`);
    p();
    p(`**Visual direction:** ${content.visualDirection}`);
    p();
    if (content.colorPalette.length) {
      p(`**Colour palette:**`);
      for (const c of content.colorPalette) p(`- ${c.role}: ${c.name} \`${c.hex}\``);
      p();
    }
  } else {
    p(`Brand colours: ${listToSentence(s.brandColors) || "—"}. Style: ${s.stylePreference || "—"}.`);
    p();
  }

  // D. Site Map
  p(`## D. Site Map`);
  if (content?.recommendedStructure.length) {
    for (const r of content.recommendedStructure) p(`- **${r.page}** — ${r.purpose}`);
  } else {
    for (const pg of s.pages) p(`- ${pg}`);
  }
  p();

  // E. Page Copy
  p(`## E. Page Copy`);
  if (content) {
    p(`- **Hero headline:** ${content.heroHeadline}`);
    p(`- **Hero subheadline:** ${content.heroSubheadline}`);
    p(`- **Primary CTA:** ${content.primaryCta}`);
    p(`- **Secondary CTA:** ${content.secondaryCta}`);
    p(`- **Contact section:** ${content.contactSectionText}`);
    p(`- **Footer:** ${content.footerContent}`);
    p();
  }
  for (const pg of pages) {
    p(`### ${pg.title}`);
    for (const sec of pg.sections) {
      p(`**${sec.heading}**`);
      p();
      p(sec.body);
      p();
    }
  }

  // F. SEO Metadata
  p(`## F. SEO Metadata`);
  for (const m of seo) {
    p(`### ${m.pageTitle}`);
    p(`- Title: ${m.title}`);
    p(`- Description: ${m.description}`);
    if (m.keywords.length) p(`- Keywords: ${m.keywords.join(", ")}`);
    p();
  }

  // G. Assets
  p(`## G. Assets`);
  p(`- Logo: ${s.logoUrl || "(none provided)"}`);
  if (s.imageUrls.length) {
    p(`- Images:`);
    for (const url of s.imageUrls) p(`  - ${url}`);
  } else {
    p(`- Images: (none provided)`);
  }
  const extraAssets = assets.filter((a) => a.type === "document" || a.type === "link");
  if (extraAssets.length) {
    p(`- Other:`);
    for (const a of extraAssets) p(`  - ${a.label}: ${a.url}`);
  }
  if (content?.imagePlacement.length) {
    p(`- Placement notes:`);
    for (const n of content.imagePlacement) p(`  - ${n}`);
  }
  p();

  // H. Contact Info
  p(`## H. Contact Info`);
  p(`- Phone (on site): ${phone}`);
  p(`- Email (on site): ${email}`);
  if (s.socialLinks.length) {
    p(`- Social: ${s.socialLinks.map((l) => `${l.label} ${l.url}`).join(", ")}`);
  }
  p();

  // I. Domain Info
  p(`## I. Domain Info`);
  if (s.hasDomain && s.domain) {
    p(`- Client has a domain: **${s.domain}**`);
    p(`- Action: connect this domain to Netlify and configure DNS + SSL.`);
  } else {
    p(`- Client does **not** have a domain.`);
    p(`- Offer the personalised URL/domain add-on (from ${formatCurrency(settings.defaultDomainAddOnPrice)}).`);
  }
  p(`- Domain status: ${project.domainStatus.replace(/_/g, " ")}`);
  p();

  // J. Design Inspiration
  p(`## J. Design Inspiration`);
  if (s.inspirationSites.length) {
    for (const url of s.inspirationSites) p(`- ${url}`);
    p();
    if (content?.inspirationSummary) p(content.inspirationSummary);
  } else {
    p(`- None provided.`);
    if (content?.inspirationSummary) {
      p();
      p(content.inspirationSummary);
    }
  }
  p();

  // K. Required Features
  p(`## K. Required Features`);
  p(`- Responsive, mobile-first layout`);
  p(`- Working contact form (Netlify Forms) routed to ${email}`);
  p(`- Per-page SEO titles + meta descriptions (section F)`);
  p(`- Open Graph / social share tags + JSON-LD LocalBusiness schema`);
  p(`- Google tracking placeholder (${settings.googleTrackingId || "G-XXXXXXXXXX"})`);
  p(`- Meta/Facebook pixel placeholder (${settings.metaPixelId || "set later"})`);
  p(`- Accessibility (WCAG AA)`);
  p(`- Favicon + touch icons`);
  if (settings.cayworksAdsEngineUrl) {
    p(`- Integration-ready for Cayworks Ads Engine (${settings.cayworksAdsEngineUrl})`);
  }
  p();

  // L. Deployment Checklist
  p(`## L. Deployment Checklist`);
  const items = project.checklist.length
    ? project.checklist
    : settings.defaultChecklistItems.map((label) => ({ id: label, label, done: false }));
  for (const item of items) p(`- [${item.done ? "x" : " "}] ${item.label}`);
  p();

  // M. Build prompt
  p(`## M. Claude / Codex Build Prompt`);
  p("```text");
  p(buildHandoffPrompt(bundle, settings));
  p("```");
  p();

  return L.join("\n");
}

export interface WebsiteBuildPackageJson {
  generatedBy: string;
  generatedAt: string;
  clientInfo: ProjectBundle["submission"];
  project: ProjectBundle["project"];
  businessSummary?: string;
  brandDirection?: ProjectBundle["content"];
  siteMap: { page: string; purpose: string }[];
  pages: ProjectBundle["pages"];
  seo: ProjectBundle["seo"];
  assets: ProjectBundle["assets"];
  handoffPrompt: string;
}

export function buildPackageJson(
  bundle: ProjectBundle,
  settings: SystemSettings,
): WebsiteBuildPackageJson {
  return {
    generatedBy: `${settings.companyName} WebBuilder Workspace`,
    generatedAt: new Date().toISOString(),
    clientInfo: bundle.submission,
    project: bundle.project,
    businessSummary: bundle.content?.businessSummary,
    brandDirection: bundle.content,
    siteMap:
      bundle.content?.recommendedStructure ??
      bundle.submission.pages.map((page) => ({ page, purpose: "" })),
    pages: bundle.pages,
    seo: bundle.seo,
    assets: bundle.assets,
    handoffPrompt: buildHandoffPrompt(bundle, settings),
  };
}
